# Generated by Django 4.2.24 on 2025-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0002_locataire_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='meublé',
            field=models.BooleanField(default=True),
        ),
    ]
