# Generated by Django 4.2.24 on 2025-11-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0003_property_meublé'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
