# Generated by Django 4.2.24 on 2025-11-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0005_remove_user_image_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('proprietaire', 'Proprietaire'), ('user', 'Utilisateur'), ('locataire', 'Locataire')], default='proprietaire', max_length=20),
        ),
    ]
