# Generated by Django 4.2.24 on 2025-11-06 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='proprietaire_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locataire',
            name='user_locataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_locataire', to=settings.AUTH_USER_MODEL),
        ),
    ]
