# Generated by Django 4.2.24 on 2025-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0007_locataire_proprietaire_user_locataire_user_locataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
