# Generated by Django 4.2.24 on 2025-11-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0008_user_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='identifiant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
