# Generated by Django 4.2.24 on 2025-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0010_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='garantie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
