# Generated by Django 4.2.24 on 2025-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0011_alter_location_garantie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
