# Generated by Django 4.2.24 on 2025-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0012_alter_locataire_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
