# Generated by Django 4.2.24 on 2025-12-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0013_locataire_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheanceLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé'), ('en_retard', 'En retard')], max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bailti.location')),
            ],
        ),
    ]
