# Generated by Django 4.2.24 on 2025-12-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0014_echeanceloyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcheanceLoyer',
            new_name='Quittance',
        ),
    ]
