# Generated by Django 4.2.24 on 2025-12-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0015_rename_echeanceloyer_quittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quittance',
            name='statut',
        ),
        migrations.AddField(
            model_name='quittance',
            name='annee',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quittance',
            name='status',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='non_paye', max_length=20),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='mois',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
