# Generated by Django 4.2.24 on 2025-12-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bailti', '0016_remove_quittance_statut_quittance_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locataire', to='bailti.locataire'),
        ),
    ]
